version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: silver_user
      POSTGRES_PASSWORD: silver_password
      POSTGRES_DB: silver_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
